#!/usr/bin/env python3
"""Build the glyph table Kronos captions draw from.

Captions use the game's own LanaPixel font (resources/font/cjk/lanapixel.fnt in
Repentance+). They are drawn from its atlas through a Sprite rather than the Font
API, so each letter can crumble into dust like the item sprite. This script reads
the font's metrics and atlas from the extracted game resources and writes, for
every character used in scripts/locale, its atlas rectangle, offsets, advance and
the 2x2 cells that hold ink (the dust grains).

    python generate_caption_glyphs.py            write the table
    python generate_caption_glyphs.py --check    fail if the table is out of date

Run it after locale text gains characters; check_locale.py reports any caption
character missing from the table. Needs Pillow and the extracted game resources
(../../extracted_resources, made with the game's Resource Extractor).
"""
import argparse
import os
import struct
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)
import lua_data  # noqa: E402

FONT = os.path.normpath(os.path.join(ROOT, "..", "..", "extracted_resources", "resources", "font", "cjk", "lanapixel.fnt"))
ATLAS_RUNTIME_PATH = "font/cjk/lanapixel_0.png"
LOCALE_DIR = os.path.join(ROOT, "scripts", "locale")
OUTPUT = os.path.join(ROOT, "scripts", "items", "collectibles", "kronos_caption_glyphs.lua")
CELL = 2  # dust grain size in pixels, the same as the item sprite's grains
ALWAYS = "".join(chr(c) for c in range(32, 127))  # digits and signs for live values


def parse_font(path):
    data = open(path, "rb").read()
    if data[:4] != b"BMF\x03":
        sys.exit("generate_caption_glyphs: %s is not a binary BMFont v3 file" % path)
    font, pos = {"chars": {}}, 4
    while pos < len(data):
        kind, size = data[pos], struct.unpack_from("<I", data, pos + 1)[0]
        body = data[pos + 5:pos + 5 + size]
        if kind == 2:
            font["lineHeight"], font["base"], font["scaleW"], font["scaleH"], font["pages"] = struct.unpack_from("<HHHHH", body)
        elif kind == 3:
            font["pageFiles"] = [name.decode() for name in body.split(b"\0")[:-1]]
        elif kind == 4:
            for i in range(size // 20):
                cid, x, y, w, h, xo, yo, xa, page, _ = struct.unpack_from("<IHHHHhhhBB", body, i * 20)
                font["chars"][cid] = (x, y, w, h, xo, yo, xa, page)
        pos += 5 + size
    if font.get("pages") != 1:
        sys.exit("generate_caption_glyphs: expected a single atlas page")
    return font


def locale_strings(value):
    if isinstance(value, str):
        yield value
    elif isinstance(value, list):
        for inner in value:
            yield from locale_strings(inner)
    elif isinstance(value, dict):
        for inner in value.values():
            yield from locale_strings(inner)


def used_characters():
    chars = set(ALWAYS)
    for name in sorted(os.listdir(LOCALE_DIR)):
        if name.endswith(".lua") and name != "init.lua":
            for text in locale_strings(lua_data.load(os.path.join(LOCALE_DIR, name))):
                chars.update(text)
    return sorted(ch for ch in chars if ch >= " ")


def ink_cells(alpha, x, y, w, h):
    cells = []
    columns = (w + CELL - 1) // CELL
    for cy in range((h + CELL - 1) // CELL):
        for cx in range(columns):
            for py in range(y + cy * CELL, min(y + h, y + cy * CELL + CELL)):
                if any(alpha[px, py] for px in range(x + cx * CELL, min(x + w, x + cx * CELL + CELL))):
                    cells.append(cy * columns + cx)
                    break
    return cells


def build():
    from PIL import Image

    if not os.path.exists(FONT):
        sys.exit("generate_caption_glyphs: %s not found; extract the game resources first" % FONT)
    font = parse_font(FONT)
    folder = os.path.dirname(FONT)
    files = {name.lower(): name for name in os.listdir(folder)}
    atlas = Image.open(os.path.join(folder, files[font["pageFiles"][0].lower()])).convert("RGBA")
    alpha = atlas.getchannel("A").load()

    lines, missing = [], []
    for ch in used_characters():
        glyph = font["chars"].get(ord(ch))
        if glyph is None:
            missing.append(ch)
            continue
        x, y, w, h, xo, yo, xa, _ = glyph
        cells = ink_cells(alpha, x, y, w, h) if w and h else []
        lines.append("        [%d] = { %d, %d, %d, %d, %d, %d, %d, { %s } },"
                     % (ord(ch), x, y, w, h, xo, yo, xa, ", ".join(str(c) for c in cells)))

    header = (
        "-- Generated by generate_caption_glyphs.py from the game's LanaPixel font\n"
        "-- (resources/font/cjk/lanapixel.fnt). Do not edit; rerun the script instead.\n"
        "-- glyphs[codepoint] = { atlas x, y, width, height, x offset, y offset, x advance,\n"
        "--     { ink cells: row * ceil(width / cell) + column } }\n"
    )
    body = (
        "return {\n"
        '    atlas = "%s",\n'
        "    atlasWidth = %d,\n"
        "    atlasHeight = %d,\n"
        "    lineHeight = %d,\n"
        "    base = %d,\n"
        "    cell = %d,\n"
        "    glyphs = {\n%s\n    },\n"
        "}\n"
    ) % (ATLAS_RUNTIME_PATH, font["scaleW"], font["scaleH"], font["lineHeight"], font["base"], CELL, "\n".join(lines))
    return header + body, missing


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed table is out of date")
    args = parser.parse_args()
    text, missing = build()
    if missing:
        print("generate_caption_glyphs: LanaPixel has no glyph for: %s" % " ".join("U+%04X" % ord(c) for c in missing))
    current = open(OUTPUT, encoding="utf-8").read() if os.path.exists(OUTPUT) else None
    if args.check:
        if current != text:
            sys.exit("generate_caption_glyphs: %s is out of date; run python generate_caption_glyphs.py" % OUTPUT)
        print("generate_caption_glyphs: up to date")
        return
    if current == text:
        print("generate_caption_glyphs: unchanged")
        return
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print("generate_caption_glyphs: wrote %s (%d glyphs)" % (OUTPUT, text.count("\n        [")))


if __name__ == "__main__":
    main()
