-- Adopt the rooms generated by the real Death Certificate effect. This module
-- never registers RoomConfigs, places rooms, or changes RoomDescriptor.Data.
ConchBlessing.DeathCertificateGalleryRooms = {}
local M = ConchBlessing.DeathCertificateGalleryRooms
local GRAPH_VERSION = 1
local DC_DIMENSION = 2
M.ENTRANCE_GRID_INDEX = 80

function M.isAvailable()
    local rgon = rawget(_G, "REPENTOGON")
    local level = Game():GetLevel()
    local descriptor = level and level:GetCurrentRoomDesc()
    if type(rgon) ~= "table" or rgon.Real ~= true or not descriptor
        or type(descriptor.GetDimension) ~= "function"
        or type(level.GetRooms) ~= "function"
        or type(level.UpdateVisibility) ~= "function"
    then return false, "repentogon_incompatible" end
    return true
end

local function descriptors()
    local available, reason = M.isAvailable()
    if not available then return nil, reason end
    local result = {}
    local ok, failure = pcall(function()
        local rooms = Game():GetLevel():GetRooms()
        for index = 0, rooms.Size - 1 do
            local descriptor = rooms:Get(index)
            if descriptor and descriptor.Data and descriptor:GetDimension() == DC_DIMENSION then
                result[#result + 1] = descriptor
            end
        end
    end)
    if not ok then return nil, tostring(failure) end
    table.sort(result, function(a, b) return a.ListIndex < b.ListIndex end)
    return result
end

function M.isDimensionEmpty()
    local rooms, reason = descriptors()
    if not rooms then return nil, reason end
    return #rooms == 0
end

local function pedestalSlots(data)
    local positions = {}
    local spawns = data.Spawns
    if not spawns or type(spawns.Get) ~= "function" or not tonumber(spawns.Size) then
        return nil, "room_spawns_unavailable"
    end
    for index = 0, spawns.Size - 1 do
        local spawn = spawns:Get(index)
        if not spawn or type(spawn.PickEntry) ~= "function" then
            return nil, "room_spawn_unavailable"
        end
        local entries = tonumber(spawn.EntryCount)
        if not entries or entries < 1 then return nil, "room_spawn_entries_unavailable" end
        -- Vanilla DC pedestal entries are unambiguous. Do not sample an RNG or
        -- guess a collectible location from a mixed/weighted spawn stack.
        local entry = spawn:PickEntry(0)
        if entry and entry.Type == EntityType.ENTITY_PICKUP
            and entry.Variant == PickupVariant.PICKUP_COLLECTIBLE then
            if entries ~= 1 then return nil, "ambiguous_pedestal_spawn" end
            positions[#positions + 1] = { x = spawn.X + 1, y = spawn.Y + 1 }
        end
    end
    return positions
end

local function identity(descriptor)
    local data = descriptor.Data
    return {
        listIndex = descriptor.ListIndex,
        gridIndex = descriptor.GridIndex,
        safeGridIndex = descriptor.SafeGridIndex,
        spawnSeed = descriptor.SpawnSeed,
        shape = data.Shape, variant = data.Variant, subtype = data.Subtype,
        roomType = data.Type, stageId = data.StageID, name = data.Name,
        doors = data.Doors,
    }
end

local function matches(descriptor, manifest)
    if not descriptor or not descriptor.Data or descriptor:GetDimension() ~= DC_DIMENSION then
        return false
    end
    local live = identity(descriptor)
    for key, value in pairs(live) do
        if value ~= manifest[key] then return false end
    end
    local positions = pedestalSlots(descriptor.Data)
    if not positions or #positions ~= manifest.capacity
        or type(manifest.pedestalPositions) ~= "table" then return false end
    for slot, position in ipairs(positions) do
        local saved = manifest.pedestalPositions[slot]
        if not saved or position.x ~= saved.x or position.y ~= saved.y then return false end
    end
    return true
end

function M.capture(catalog, seed)
    local rooms, reason = descriptors()
    if not rooms then return nil, reason end
    if #rooms == 0 then return nil, "death_certificate_not_generated" end
    local graph = {
        version = GRAPH_VERSION, dimension = DC_DIMENSION, seed = seed,
        rooms = {}, catalogCount = #catalog, complete = true,
    }
    local nextCatalogIndex = 1
    for _, descriptor in ipairs(rooms) do
        local data = descriptor.Data
        -- Extracted HOME rooms use subtype 33 for the entrance and 34 for
        -- stock. Other dimension-2 room systems must never be adopted.
        if data.StageID ~= 35 or data.Name ~= "Death Certificate"
            or (data.Subtype ~= 33 and data.Subtype ~= 34) then
            return nil, "foreign_death_certificate_room"
        end
        local manifest = identity(descriptor)
        manifest.key = "ConchBlessing:DeathCertificate:" .. tostring(manifest.listIndex)
        manifest.graphIndex = manifest.listIndex
        manifest.kind = data.Subtype == 33 and "entrance" or "stock"
        manifest.layoutKey = "vanilla:" .. tostring(data.Shape) .. ":" .. tostring(data.Variant)
        local positions, positionReason = pedestalSlots(data)
        if not positions then return nil, positionReason end
        manifest.pedestalPositions = positions
        manifest.capacity = #positions
        manifest.catalogStart = nextCatalogIndex
        manifest.slotCount = manifest.kind == "stock"
            and math.min(#positions, math.max(0, #catalog - nextCatalogIndex + 1)) or 0
        nextCatalogIndex = nextCatalogIndex + manifest.slotCount
        if manifest.kind == "entrance" then
            if graph.entrance or manifest.gridIndex ~= M.ENTRANCE_GRID_INDEX then
                return nil, "ambiguous_death_certificate_entrance"
            end
            graph.entrance = manifest
        else
            graph.rooms[#graph.rooms + 1] = manifest
        end
    end
    if not graph.entrance then return nil, "missing_death_certificate_entrance" end
    if nextCatalogIndex <= #catalog then return nil, "insufficient_death_certificate_pedestals" end
    return graph
end

local function validateAssignments(graph, expectedCatalogCount)
    local count = tonumber(graph.catalogCount)
    if not count or count < 1 or count ~= math.floor(count)
        or (expectedCatalogCount and count ~= expectedCatalogCount) then return false end
    local entrance = graph.entrance
    if type(entrance.key) ~= "string" or entrance.kind ~= "entrance" or entrance.slotCount ~= 0
        or entrance.capacity ~= 0 or entrance.gridIndex ~= M.ENTRANCE_GRID_INDEX then return false end
    local nextIndex = 1
    local keys, seeds = { [entrance.key] = true }, {}
    for _, manifest in ipairs(graph.rooms) do
        local slots = tonumber(manifest.slotCount)
        local capacity = tonumber(manifest.capacity)
        if manifest.kind ~= "stock" or type(manifest.key) ~= "string" or keys[manifest.key]
            or not slots or slots < 0 or slots ~= math.floor(slots)
            or not capacity or capacity < slots
            or manifest.catalogStart ~= nextIndex
            or slots ~= math.min(capacity, math.max(0, count - nextIndex + 1)) then
            return false
        end
        keys[manifest.key] = true
        for slot = 1, slots do
            local seed = manifest.sourceSeeds and manifest.sourceSeeds[slot]
            if manifest.initialized == true and seed == nil then return false end
            if seed ~= nil then
                if type(seed) ~= "number" or seed <= 0 or seed ~= math.floor(seed)
                    or seeds[seed] then return false end
                seeds[seed] = true
            end
        end
        nextIndex = nextIndex + slots
    end
    return nextIndex == count + 1
end

function M.rebind(graph, expectedCatalogCount)
    if type(graph) ~= "table" or graph.version ~= GRAPH_VERSION
        or graph.dimension ~= DC_DIMENSION or not graph.entrance
        or graph.complete ~= true or type(graph.rooms) ~= "table" then
        return nil, "incompatible_death_certificate_graph"
    end
    if not validateAssignments(graph, expectedCatalogCount) then
        return nil, "invalid_death_certificate_catalog_assignments"
    end
    local rooms, reason = descriptors()
    if not rooms then return nil, reason end
    local runtime = { byListIndex = {}, manifestByListIndex = {}, stockRooms = {}, descriptors = {} }
    runtime.manifestByListIndex[graph.entrance.listIndex] = graph.entrance
    for _, manifest in ipairs(graph.rooms) do
        if runtime.manifestByListIndex[manifest.listIndex] then return nil, "duplicate_manifest" end
        runtime.manifestByListIndex[manifest.listIndex] = manifest
    end
    if #rooms ~= #graph.rooms + 1 then return nil, "death_certificate_room_count_changed" end
    for _, descriptor in ipairs(rooms) do
        local manifest = runtime.manifestByListIndex[descriptor.ListIndex]
        local ok, matched = pcall(matches, descriptor, manifest)
        if not manifest or runtime.byListIndex[descriptor.ListIndex]
            or not ok or not matched then
            return nil, "death_certificate_descriptor_changed"
        end
        runtime.byListIndex[descriptor.ListIndex] = descriptor
        runtime.descriptors[#runtime.descriptors + 1] = descriptor
    end
    runtime.entrance = runtime.byListIndex[graph.entrance.listIndex]
    for index, manifest in ipairs(graph.rooms) do
        runtime.stockRooms[index] = runtime.byListIndex[manifest.listIndex]
    end
    return runtime
end

function M.getCurrentManifest(graph, runtime)
    local descriptor = Game():GetLevel():GetCurrentRoomDesc()
    local manifest = runtime and runtime.manifestByListIndex[descriptor.ListIndex]
    if manifest and matches(descriptor, manifest) then return manifest, descriptor end
end

function M.getSlotWorldPosition(room, manifest, slot)
    local position = manifest.pedestalPositions and manifest.pedestalPositions[slot]
    if not position or slot > manifest.slotCount then return nil end
    return room:GetGridPosition(position.x + position.y * room:GetGridWidth())
end

function M.removeCollectibles(manifest)
    -- The restored historical behavior replaces DC collectibles, including
    -- pedestals created by the engine on later room visits. Trinkets dropped
    -- by players and every other pickup variant remain untouched.
    if type(manifest) ~= "table"
        or not matches(Game():GetLevel():GetCurrentRoomDesc(), manifest) then return false end
    for _, entity in ipairs(Isaac.FindByType(
        EntityType.ENTITY_PICKUP, PickupVariant.PICKUP_COLLECTIBLE, -1, false, false
    )) do
        if entity:Exists() then entity:Remove() end
    end
    return true
end

function M.reveal(graph, runtime)
    local level = Game():GetLevel()
    local ok, reason = pcall(function()
        for _, descriptor in ipairs(runtime.descriptors) do
            descriptor.DisplayFlags = descriptor.DisplayFlags | 5
        end
        level:UpdateVisibility()
    end)
    return ok, ok and nil or tostring(reason)
end

return M
