-- Order is shared by the console viewer and the standalone HTML preview.
-- A pending concept retains the existing flag-based animation in game.
return {
    { key = "LIVE_EYE" },
    { key = "VOID_DAGGER", effect = "void", impact = 51 },
    { key = "ETERNAL_FLAME" },
    { key = "POWER_TRAINING" },
    { key = "ORAL_STEROIDS" },
    { key = "INJECTABLE_STEROIDS" },
    { key = "DRAGON", effect = "lightning", impact = 45, nativeResult = true },
    { key = "KRONOS", effect = "devour", nativeResult = true },
    { key = "APPRAISAL_CERTIFICATE" },
    { key = "MONEY_TEAR", effect = "rain", impact = 54, duration = 132 },
    { key = "UTILITY_BELT" },
    { key = "SEALED_DEMON_SWORD" },
    { key = "TYRFING" },
    { key = "ICE_BREATH", effect = "ice", impact = 45 },
    { key = "FIRE_BREATH", effect = "fire", impact = 45 },
    { key = "SOFLAM", effect = "missile", impact = 53 },
    { key = "TWO_FACED_PENNY" },
    { key = "SEVERED_OATH" },
    { key = "CEIL" },
    { key = "ROUND" },
    { key = "FLOOR" },
    { key = "REAL_EYES" },
    { key = "AR_GLASSES" },
    { key = "HEMISPATIAL_NEGLECT" },
    { key = "TIME_MONEY", effect = "clock_coin", impact = 48 },
    { key = "TIME_POWER", effect = "clock_power", impact = 48 },
    { key = "TIME_TEAR", effect = "clock_rain", impact = 54, duration = 132 },
    { key = "TIME_LUCK", effect = "clock_luck", impact = 48 },
    { key = "F_MINUS" },
    { key = "C_MINUS" },
    { key = "B_MINUS" },
    { key = "A_MINUS" },
    { key = "ATROPOS" },
    -- Both crowns have visible bounds (4,10)-(29,28) in their 32px art.
    -- Effects follow the crown's silhouette centre, not transparent padding.
    { key = "ANGELS_CROWN", effect = "purify", impact = 41, anchorX = 16.5, anchorY = 19 },
}
