-- Order is shared by the console viewer and the standalone HTML preview.
-- A pending concept retains the existing flag-based animation in game.
return {
    { key = "LIVE_EYE" },
    { key = "VOID_DAGGER", effect = "void", impact = 51 },
    { key = "ETERNAL_FLAME" },
    { key = "POWER_TRAINING" },
    { key = "ORAL_STEROIDS" },
    { key = "INJECTABLE_STEROIDS" },
    { key = "DRAGON", effect = "lightning", impact = 45 },
    { key = "KRONOS" },
    { key = "APPRAISAL_CERTIFICATE" },
    { key = "MONEY_TEAR", effect = "rain", impact = 54 },
    { key = "UTILITY_BELT" },
    { key = "SEALED_DEMON_SWORD" },
    { key = "TYRFING" },
    { key = "ICE_BREATH", effect = "ice", impact = 45 },
    { key = "FIRE_BREATH", effect = "fire", impact = 45 },
    { key = "SOFLAM", effect = "missile", impact = 53 },
    { key = "TWO_FACED_PENNY" },
    { key = "SEVERED_OATH" },
    { key = "CEIL" },
    { key = "ROUND" },
    { key = "FLOOR" },
    { key = "TIME_MONEY", effect = "clock_coin", impact = 48 },
    { key = "TIME_POWER", effect = "clock_power", impact = 48 },
    { key = "TIME_TEAR", effect = "clock_rain", impact = 54 },
    { key = "TIME_LUCK", effect = "clock_luck", impact = 48 },
    { key = "F_MINUS", effect = "grade", impact = 48 },
    { key = "C_MINUS", effect = "grade", impact = 48 },
    { key = "B_MINUS", effect = "grade", impact = 48 },
    { key = "A_MINUS", effect = "grade", impact = 48 },
    { key = "ATROPOS", effect = "thread", impact = 48 },
    { key = "ANGELS_CROWN", effect = "purify", impact = 41 },
}
