-- Independent expectations transcribed from the player-facing synergy contract.
-- Do not populate expected values from kronos.data or its implementation tables.
return {
    ["twisted_pair"] = {  },
    ["succubus"] = {  },
    ["incubus"] = {  },
    ["seraphim"] = { grant = "SACRED_HEART", cap = 1 },
    ["robo_baby"] = { grant = "TECHNOLOGY", cap = 0 },
    ["robo_baby_2"] = { grant = "TECHNOLOGY_2", cap = 0 },
    ["blue_babys_only_friend"] = { grant = "LUDOVICO_TECHNIQUE", cap = 1 },
    ["lil_brimstone"] = { grant = "BRIMSTONE", cap = 0 },
    ["bobs_brain"] = { grant = "IPECAC", cap = 1 },
    ["lil_monstro"] = { grant = "MONSTROS_LUNG", cap = 1 },
    ["lil_haunt"] = {  },
    ["blood_puppy"] = { grant = "GIMPY", cap = 1 },
    ["angelic_prism"] = {  },
    ["bot_fly"] = { grant = "LOST_CONTACT", cap = 1 },
    ["freezer_baby"] = { grant = "URANUS", cap = 1 },
    ["lil_abaddon"] = { grant = "MAW_OF_THE_VOID", cap = 1 },
    ["multidimensional_baby"] = { grant = "20_20", cap = 0 },
    ["harlequin_baby"] = { grant = "THE_WIZ", cap = 0 },
    ["brother_bobby"] = {  },
    ["demon_baby"] = { grant = "MARKED", cap = 1 },
    ["little_gish"] = {  },
    ["lil_loki"] = { grant = "LOKIS_HORNS", cap = 0 },
    ["ghost_baby"] = { grant = "CONTINUUM", cap = 0 },
    ["rotten_baby"] = {  },
    ["little_steven"] = {  },
    ["rainbow_baby"] = { grant = "FRUIT_CAKE", cap = 1 },
    ["guardian_angel"] = {  },
    ["censer"] = {  },
    ["leech"] = { grant = "CHARM_VAMPIRE", cap = 1 },
    ["bomb_bag"] = { grant = "PYRO", cap = 1 },
    ["dark_bum"] = { grant = "MITRE", cap = 1 },
    ["key_bum"] = { grant = "SKELETON_KEY", cap = 1 },
    ["abel"] = { grant = "MY_REFLECTION", cap = 1 },
    ["star_of_bethlehem"] = { grant = "COMPASS", cap = 1 },
    ["farting_baby"] = { grant = "JELLY_BELLY", cap = 1 },
    ["samsons_chains"] = { grant = "THUNDER_THIGHS", cap = 1 },
    ["finger"] = { grant = "TRACTOR_BEAM", cap = 1 },
    ["little_chad"] = { grant = "CANDY_HEART", cap = 1 },
    ["sack_of_pennies"] = { grant = "DOLLAR", cap = 1 },
    ["sack_of_sacks"] = { grant = "SACK_HEAD", cap = 1 },
    ["charged_baby"] = { grant = "9_VOLT", cap = 1 },
    ["yo_listen"] = { grant = "XRAY_VISION", cap = 1 },
    ["daddy_longlegs"] = {  },
    ["sister_maggy"] = { grant = "CRICKETS_HEAD", cap = 1 },
    ["little_chubby"] = { grant = "MARS", cap = 1 },
    ["big_chubby"] = { grant = "MARS", cap = 1, block = 0.01 },
    ["peeper"] = { grant = "MOMS_EYE", cap = 1 },
    ["bbf"] = { grant = "FIRE_MIND", cap = 1 },
    ["fates_reward"] = { grant = "20_20", cap = 1 },
    ["lil_gurdy"] = { grant = "CHOCOLATE_MILK", cap = 1 },
    ["bumbo"] = { grant = "PIGGY_BANK", cap = 1 },
    ["spider_mod"] = { grant = "SPIDER_BITE", cap = 1 },
    ["depression"] = { grant = "HOLY_LIGHT", cap = 1 },
    ["king_baby"] = { grant = "MAGIC_MUSHROOM", cap = 1 },
    ["acid_baby"] = { grant = "PHD", cap = 1 },
    ["jaw_bone"] = { grant = "COMPOUND_FRACTURE", cap = 1 },
    ["boiled_baby"] = { grant = "EYE_SORE", cap = 1 },
    ["lil_dumpy"] = { grant = "JELLY_BELLY", cap = 1 },
    ["fruity_plum"] = { grant = "KIDNEY_STONE", cap = 1 },
    ["7_seals"] = {  },
    ["juicy_sack"] = {  },
    ["sissy_longlegs"] = {  },
    ["intruder"] = {  },
    ["worm_friend"] = {  },
    ["halo_of_flies"] = { block = 0.01 },
    ["distant_admiration"] = { block = 0.01 },
    ["cube_of_meat"] = { block = 0.01 },
    ["forever_alone"] = { block = 0.01 },
    ["sacrificial_dagger"] = { block = 0.02 },
    ["guppys_hairball"] = { block = 0.01 },
    ["guillotine"] = { block = 0.01 },
    ["ball_of_bandages"] = { block = 0.01 },
    ["smart_fly"] = { block = 0.01 },
    ["best_bud"] = { block = 0.01 },
    ["big_fan"] = { block = 0.02 },
    ["punching_bag"] = { block = 0.02 },
    ["sworn_protector"] = { block = 0.05 },
    ["friend_zone"] = { block = 0.01 },
    ["lost_fly"] = { block = 0.01 },
    ["hushy"] = { block = 0.01 },
    ["moms_razor"] = { block = 0.01 },
    ["angry_fly"] = { block = 0.01 },
    ["leprosy"] = { block = 0.01 },
    ["slipped_rib"] = { block = 0.01 },
    ["pointy_rib"] = { block = 0.01 },
    ["psy_fly"] = { block = 0.05 },
    ["tinytoma"] = { block = 0.01 },
    ["headless_baby"] = { grant = "AQUARIUS", cap = 1 },
    ["cains_other_eye"] = { grant = "RUBBER_CEMENT", cap = 1 },
    ["papa_fly"] = { grant = "HIVE_MIND", cap = 1 },
    ["shade"] = { grant = "LUSTY_BLOOD", cap = 1 },
    ["obsessed_fan"] = { block = 0.01 },
    ["gemini"] = {  },
    ["cube_baby"] = {  },
    ["lil_spewer"] = {  },
    ["gb_bug"] = {  },
    ["bum_friend"] = {  },
    ["lil_chest"] = {  },
    ["relic"] = {  },
    ["mystery_sack"] = {  },
    ["rune_bag"] = {  },
    ["paschal_candle"] = {  },
    ["holy_water"] = {  },
    ["dry_baby"] = {  },
    ["milk"] = {  },
    ["bird_cage"] = {  },
    ["mystery_egg"] = {  },
    ["my_shadow"] = {  },
    ["hallowed_ground"] = {  },
    ["lost_soul"] = {  },
    ["bloodshot_eye"] = {  },
    ["mongo_baby"] = {  },
    ["buddy_in_a_box"] = {  },
    ["lil_delirium"] = {  },
    ["box_of_friends"] = {  },
    ["monster_manual"] = {  },
    ["sacrificial_altar"] = {  },
    ["trinket_the_twins"] = {  },
    ["1up"] = { excluded = true },
    ["isaacs_heart"] = { excluded = true },
    ["dead_cat"] = { excluded = true },
    ["key_piece_1"] = { excluded = true },
    ["key_piece_2"] = { excluded = true },
    ["knife_piece_1"] = { excluded = true },
    ["knife_piece_2"] = { excluded = true },
    ["damocles_passive"] = { excluded = true },
    ["straw_man"] = { excluded = true },
    ["blood_oath"] = { excluded = true },
}
